config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :ajaxcall
    end
  end
  
root "posts#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def ajaxcall
    respond_to do |format|
      format.js
    end
  end

  def index
    @posts = Post.all
  end


  def show
  end


  def new
    @post = Post.new
    respond_to do |format|
      format.js
    end
  end


  def edit
    respond_to do |format|
      format.js
    end
  end


  def create
     @posts = Post.all
     @post = Post.create(post_params)
  end


  def update
    @posts = Post.all
     @post.update(post_params)
  
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxcrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_ajax.html.erb
ajax call test

app/views/posts/_edit.html.erb
<%= form_for([@post], :remote => true, :method => "PUT") do |f| %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post, :remote => true %></td>
             <td><%= link_to 'ajaxcall', ajaxcall_posts_path, :remote => true %></td>
        <td><%= link_to 'Edit', edit_post_path(post), :remote => true %></td>
        <td><%= link_to 'Destroy', post, method: :delete, :remote => true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="ajax">
<%= link_to 'New Post', new_post_path, :remote => true %>
</div>

app/views/posts/_new.html.erb
<%= form_for([@post], :remote => true, :method => "POST") do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/create.js.erb
$(".lists").html('<%= escape_javascript(render 'index') %>');

app/views/posts/destroy.js.erb
window.location.reload();

app/views/posts/edit.js.erb
$("#ajax").html('<%= escape_javascript(render 'edit') %>'); 

app/views/posts/index.html.erb
<div class="lists">
  <%= render "index" %>
 </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
<%#= render 'form' %>
$("#ajax").html('<%= escape_javascript(render 'new') %>');
<%#= link_to 'Back', posts_path %>

app/views/posts/show.js.erb
$("#ajax").html('<%= escape_javascript(render 'show') %>');

app/views/posts/update.js.erb
$(".lists").html('<%= escape_javascript render :partial => 'index' %>'); 